# -*- coding: utf-8 -*-
"""Exercise1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1foZhU9PiuUuAzHnj5xHJyTHxxI2NSYkj

#Exercise 1

##Q1
"""

print("*******__________________")
print("*******__________________")
print("*******__________________")
print("*******__________________")
print("*******__________________")
print("_________________________")
print("_________________________")
print("_________________________")
print("_________________________")

"""##Q2"""

print("      *      ")
print("     ***     ")
print("    *****    ")
print("   *******   ")
print("  *********  ")
print(" *********** ")
print("     |||     ")

"""##Q3"""

print(" ^;^ ")
print("  |  ")
print("./|\.")
print("  |  ")
print("_/ \_")

"""##Q4"""

x = int(6)
y = int(7)
z = x+y
print(z)

"""##Q5"""

num = int(input("Enter a number between 1 and 300: "))
print("Result: ", num+1)

"""##Q6"""

num1 = int(input("Enter a number: "))
num2 = int(input("Enter a number: "))
num3 = num1+num2
print (num3)

"""##Q7"""

num1 = int(input("Enter a number: "))
num2 = int(input("Enter a number: "))
num3 = num1/num2
print (num3)